Development
Cena-JM/weather-app pull request #1
Opened 2019-07-22 00:50 UTC by Cena-JM

2019-07-22 06:35 UTC, dipto0321 requested changes
Hi @Cena-JM ,

Good job 👏 . This project is good. Here is the checklist for the application.

#### Application
- [x] It allows the user to search for a specific location
- [ ] It has a toggle control to determine if the result will be shown in Celsius or Fahrenheit
- [x] It changes its appearance based on the received data
- [x] It uses either `promises` or `async/await`

Please add that unchecked feature and send another request to re-review this project.

Thanks 🙏

2019-07-22 06:35 UTC, dipto0321 commented on src/controller.js
> +const processWeatherdesc = (condition) => {
**Optional tips:** Switch is the best choice for handling this operation. If you want then you can implement switch.

2019-07-22 11:59 UTC, dipto0321 commented
Hi @Cena-JM ,

Good job 👏 . I liked the feature which you added. Don't remove this feature. Just add the actual feature with it as I discussed with you on slack and send another request to final review this project.

Thanks 🙏

2019-07-23 01:13 UTC, rvvergara commented
Hi @Cena-JM and @dipto0321,

The last item in the checklist has already been satisfied (toggle button that converts between C and F). So I guess it's a 

# :+1: 

I'm not aware of the subject of the Slack conversation so if @dipto0321 has discussed something else that you need, @Cena-JM, then his veto will overrule this thumbs up.. But unless and until that happens this stands.

2019-07-23 08:37 UTC, merged